### ISSUE TITLE
updating to Java 11 broke all my servers

### ISSUE THREAD

**Issue by campbebj** [binhex/arch-mineos-node#1]
when you posted the update to java 11 all my fabric servers stopped working. it looks like the way fabric mods are loaded uses something no longer available in JVM 11. is there a way for me to lock my docker template to the previous one?

**Comment by binhex** [comment]
you can use this image and tag name to use the previously built image:-
```
binhex/arch-mineos-node:2cd410a44e4873ebb215048d51509be07bacd89a-01
```

**Comment by campbebj** [comment]
thanks!
