### ISSUE TITLE
Java 16 with Snapshot 21w19a

### ISSUE THREAD

**Issue by jeffreyrdubois** [binhex/arch-mineos-node#2]
When I updated my minecraft server to use the 21w19a snapshot profile it appears it won't start anymore. I can downgrade to 21w18a and it will start fine. I notice in Minecraft's changelogs that Java 16 is now being used. Perhaps the docker needs to be updated to include Java 16? I am not super experienced in this stuff so I could be way off.

**Comment by ThomasHineXYZ** [comment]
@jeffreyrdubois You'll most likely want to post this on to the actual MineOS Github page and not this one. This repo is just meant for being a Docker container.

https://github.com/hexparrot/mineos

**Comment by binhex** [comment]
The docker image now includes Java 8 Java 11 and Java 16, how you tell mineos to start a particular server with Java 16 I don't know, but it is now available

**Comment by Flexz9** [comment]
2021-06-12 22:57:11.723267 [info] JAVA_VERSION defined as '16'
'/usr/lib/jvm/java-16-openjdk' is not a valid Java environment path

How do we get java-16-openjdk installed on the docker? while it doesn't start

Edit: Privileged: true on unraid is required

**Comment by guizaodev** [comment]
inside unraid terminal you can run 
```bash
docker exec -it -u root [CONTAINER ID] bash
curl -O https://download.java.net/java/GA/jdk16.0.1/7147401fd7354114ac51ef3e1328291f/9/GPL/openjdk-16.0.1_linux-x64_bin.tar.gz
tar zxvf openjdk-16.0.1_linux-x64_bin.tar.gz
mv jdk-16* /usr/local/
```
then inside server's folder (appdata\binhex-mineos-node\mineos\games\servers) you go to your server.config and change java_binary to this:
```config
[java]
java_binary=/usr/local/jdk-16.0.1/bin/java
java_xmx=[YOUR CONFIGURATION]
jarfile=[YOUR CONFIGURATION]
java_xms=[YOUR CONFIGURATION]

[onreboot]
start=[YOUR CONFIGURATION]

[minecraft]
profile=[YOUR CONFIGURATION]
broadcast=[YOUR CONFIGURATION]
unconventional=[YOUR CONFIGURATION]
```

**Comment by binhex** [comment]
> inside unraid terminal you can run
> 
> ```shell
> docker exec -it -u root [CONTAINER ID] bash
> curl -O https://download.java.net/java/GA/jdk16.0.1/7147401fd7354114ac51ef3e1328291f/9/GPL/openjdk-16.0.1_linux-x64_bin.tar.gz
> tar zxvf openjdk-16.0.1_linux-x64_bin.tar.gz
> mv jdk-16* /usr/local/
> ```
> 
> then inside server's folder (appdata\binhex-mineos-node\mineos\games\servers) you go to your server.config and change java_binary to this:
> 
> ```
> [java]
> java_binary=/usr/local/jdk-16.0.1/bin/java
> java_xmx=[YOUR CONFIGURATION]
> jarfile=[YOUR CONFIGURATION]
> java_xms=[YOUR CONFIGURATION]
> 
> [onreboot]
> start=[YOUR CONFIGURATION]
> 
> [minecraft]
> profile=[YOUR CONFIGURATION]
> broadcast=[YOUR CONFIGURATION]
> unconventional=[YOUR CONFIGURATION]
> ```

this is not required, you simply set ```JAVA_VERSION ``` to 'latest' and you will get java 16 (at present) installed,
