### ISSUE TITLE
Web UI isn't working

### ISSUE THREAD

**Issue by ThomasHineXYZ** [binhex/arch-mineos-node#3]
I tried installing this on my Unraid server, and when I launch the web UI and login with `root` and `mineos` as the username and password, it ends up giving me this:

![Screenshot from 2021-06-06 23-29-45](https://user-images.githubusercontent.com/6890628/120969600-33172300-c71f-11eb-9566-8f2fa25ee7e9.png)

If I try to reload the page, it then gives me an "Unable to connect" and refuses to do anything unless I restart the container. But then this whole process starts over again.

**Comment by ThomasHineXYZ** [comment]
Just to make things clear, I didn't change any of the settings from the template that you have in the Community Apps repository.

![image](https://user-images.githubusercontent.com/6890628/120969825-7ec9cc80-c71f-11eb-888c-8bda52ff3cfe.png)
![image](https://user-images.githubusercontent.com/6890628/120969977-a3be3f80-c71f-11eb-9efa-85710f0bedef.png)

**Comment by binhex** [comment]
Your issue is caused by logging in as user root, you need to login as user nobody

**Comment by ThomasHineXYZ** [comment]
Oof... I am pretty new to containers, so I forget about that. Thank you.
